### ISSUE TITLE
Lỗi Item qty của Order trong grid Prepare Fulfil

### ISSUE THREAD

**Issue by abel274** [Magestore/OrderSuccess#7]
1. Create new order với 2 item khác nhau
2. Go to admin > Fulfillment > Verify > Prepare
Actual result: Tại gird, show sai total item Qty của order
http://prntscr.com/k5yx2y
Relate issue: https://github.com/Magestore/FulfilSuccess-M2/issues/21

**Comment by abel274** [comment]
1. Nguyên nhân: Sai phần tính toán trong dataprovider
2. Giải pháp: sửa lại dataprovider để tính đúng dữ liệu đầu ra
3. Đã test lại luồng của fulfil ở step 1, 2 và cam kết không ảnh hưởng đến những phần kể trên

**Comment by Ruby10291** [comment]
Đã test done trên CE224
- Test đã show đúng trường [Qty] của step [Prepare fulfil] và các step sau đó vs TH sp: simple, config, bundle,
